/*******************************************************/
/**  Autogenerated phoneset trees for lvl_is    */
/*******************************************************/

#include "cst_string.h"
#include "cst_phoneset.h"
extern const cst_phoneset lvl_is_phoneset;


static const char * const lvl_is_featnames[] = {
 "vc",
 "cplace",
 "ctype",
 "cvox",
 "casp",
 "vfrontness",
 "vcloseness",
 "vroundness",
 "dfrontness2",
 "dcloseness2",
 "droundness2",
 "vlength",
 NULL };

static const char * const lvl_is_phonenames[] = {
 "p",
 "ph",
 "m",
 "mz",
 "f",
 "v",
 "t",
 "th",
 "D",
 "T",
 "n",
 "nz",
 "l",
 "lz",
 "r",
 "rz",
 "s",
 "c",
 "ch",
 "j",
 "C",
 "J",
 "Jz",
 "k",
 "kh",
 "x",
 "G",
 "N",
 "Nz",
 "h",
 "i",
 "ii",
 "I",
 "II",
 "Y",
 "YY",
 "Yi",
 "oe",
 "oee",
 "E",
 "EE",
 "u",
 "uu",
 "O",
 "OO",
 "a",
 "aa",
 "Oi",
 "ou",
 "ouu",
 "ai",
 "aii",
 "au",
 "auu",
 "oei",
 "oeii",
 "ei",
 "eii",
 "pau",
 NULL };

static const int lvl_is_fv_000[] = { 0, 1, 2, 3, 4, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_001[] = { 0, 1, 2, 3, 6, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_002[] = { 0, 1, 7, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_003[] = { 0, 1, 7, 8, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_004[] = { 0, 9, 10, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_005[] = { 0, 9, 10, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_006[] = { 0, 11, 2, 3, 4, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_007[] = { 0, 11, 2, 3, 6, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_008[] = { 0, 12, 10, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_009[] = { 0, 12, 10, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_010[] = { 0, 11, 7, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_011[] = { 0, 11, 7, 8, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_012[] = { 0, 11, 13, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_013[] = { 0, 11, 13, 8, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_014[] = { 0, 11, 14, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_015[] = { 0, 11, 14, 8, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_016[] = { 0, 11, 10, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_017[] = { 0, 15, 2, 3, 4, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_018[] = { 0, 15, 2, 3, 6, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_019[] = { 0, 15, 10, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_020[] = { 0, 15, 10, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_021[] = { 0, 15, 7, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_022[] = { 0, 15, 7, 8, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_023[] = { 0, 16, 2, 3, 4, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_024[] = { 0, 16, 2, 3, 6, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_025[] = { 0, 16, 10, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_026[] = { 0, 16, 10, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_027[] = { 0, 16, 7, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_028[] = { 0, 16, 7, 8, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_029[] = { 0, 17, 10, 3, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_030[] = { 18, 5, 5, 5, 5, 19, 20, 21, 5, 5, 5, 22,   -1 };
static const int lvl_is_fv_031[] = { 18, 5, 5, 5, 5, 19, 20, 21, 5, 5, 5, 23,   -1 };
static const int lvl_is_fv_032[] = { 18, 5, 5, 5, 5, 19, 24, 21, 5, 5, 5, 22,   -1 };
static const int lvl_is_fv_033[] = { 18, 5, 5, 5, 5, 19, 24, 21, 5, 5, 5, 23,   -1 };
static const int lvl_is_fv_034[] = { 18, 5, 5, 5, 5, 19, 24, 25, 5, 5, 5, 23,   -1 };
static const int lvl_is_fv_035[] = { 18, 5, 5, 5, 5, 19, 24, 25, 5, 5, 5, 23,   -1 };
static const int lvl_is_fv_036[] = { 18, 5, 5, 5, 5, 19, 24, 25, 5, 5, 5, 22,   -1 };
static const int lvl_is_fv_037[] = { 18, 5, 5, 5, 5, 19, 26, 25, 5, 5, 5, 22,   -1 };
static const int lvl_is_fv_038[] = { 18, 5, 5, 5, 5, 19, 26, 25, 5, 5, 5, 23,   -1 };
static const int lvl_is_fv_039[] = { 18, 5, 5, 5, 5, 27, 26, 21, 5, 5, 5, 22,   -1 };
static const int lvl_is_fv_040[] = { 18, 5, 5, 5, 5, 27, 26, 21, 5, 5, 5, 23,   -1 };
static const int lvl_is_fv_041[] = { 18, 5, 5, 5, 5, 28, 20, 25, 5, 5, 5, 22,   -1 };
static const int lvl_is_fv_042[] = { 18, 5, 5, 5, 5, 28, 20, 25, 5, 5, 5, 23,   -1 };
static const int lvl_is_fv_043[] = { 18, 5, 5, 5, 5, 28, 26, 25, 5, 5, 5, 22,   -1 };
static const int lvl_is_fv_044[] = { 18, 5, 5, 5, 5, 28, 26, 25, 5, 5, 5, 23,   -1 };
static const int lvl_is_fv_045[] = { 18, 5, 5, 5, 5, 28, 29, 21, 5, 5, 5, 22,   -1 };
static const int lvl_is_fv_046[] = { 18, 5, 5, 5, 5, 28, 29, 21, 5, 5, 5, 23,   -1 };
static const int lvl_is_fv_047[] = { 30, 5, 5, 5, 5, 28, 26, 25, 19, 20, 21, 23,   -1 };
static const int lvl_is_fv_048[] = { 30, 5, 5, 5, 5, 28, 26, 25, 28, 20, 25, 22,   -1 };
static const int lvl_is_fv_049[] = { 30, 5, 5, 5, 5, 28, 26, 25, 28, 20, 25, 23,   -1 };
static const int lvl_is_fv_050[] = { 30, 5, 5, 5, 5, 28, 29, 21, 19, 20, 21, 22,   -1 };
static const int lvl_is_fv_051[] = { 30, 5, 5, 5, 5, 28, 29, 21, 19, 20, 21, 23,   -1 };
static const int lvl_is_fv_052[] = { 30, 5, 5, 5, 5, 28, 29, 21, 28, 20, 25, 22,   -1 };
static const int lvl_is_fv_053[] = { 30, 5, 5, 5, 5, 28, 29, 21, 28, 20, 25, 23,   -1 };
static const int lvl_is_fv_054[] = { 30, 5, 5, 5, 5, 28, 29, 21, 19, 24, 25, 22,   -1 };
static const int lvl_is_fv_055[] = { 30, 5, 5, 5, 5, 28, 29, 21, 19, 24, 25, 23,   -1 };
static const int lvl_is_fv_056[] = { 30, 5, 5, 5, 5, 27, 26, 21, 19, 20, 21, 22,   -1 };
static const int lvl_is_fv_057[] = { 30, 5, 5, 5, 5, 27, 26, 21, 19, 20, 21, 23,   -1 };
static const int lvl_is_fv_058[] = { 31, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,   -1 };
static const int lvl_is_fv_059[] = { 0 };

static const int * const lvl_is_fvtable[] = {
  lvl_is_fv_000, 
  lvl_is_fv_001, 
  lvl_is_fv_002, 
  lvl_is_fv_003, 
  lvl_is_fv_004, 
  lvl_is_fv_005, 
  lvl_is_fv_006, 
  lvl_is_fv_007, 
  lvl_is_fv_008, 
  lvl_is_fv_009, 
  lvl_is_fv_010, 
  lvl_is_fv_011, 
  lvl_is_fv_012, 
  lvl_is_fv_013, 
  lvl_is_fv_014, 
  lvl_is_fv_015, 
  lvl_is_fv_016, 
  lvl_is_fv_017, 
  lvl_is_fv_018, 
  lvl_is_fv_019, 
  lvl_is_fv_020, 
  lvl_is_fv_021, 
  lvl_is_fv_022, 
  lvl_is_fv_023, 
  lvl_is_fv_024, 
  lvl_is_fv_025, 
  lvl_is_fv_026, 
  lvl_is_fv_027, 
  lvl_is_fv_028, 
  lvl_is_fv_029, 
  lvl_is_fv_030, 
  lvl_is_fv_031, 
  lvl_is_fv_032, 
  lvl_is_fv_033, 
  lvl_is_fv_034, 
  lvl_is_fv_035, 
  lvl_is_fv_036, 
  lvl_is_fv_037, 
  lvl_is_fv_038, 
  lvl_is_fv_039, 
  lvl_is_fv_040, 
  lvl_is_fv_041, 
  lvl_is_fv_042, 
  lvl_is_fv_043, 
  lvl_is_fv_044, 
  lvl_is_fv_045, 
  lvl_is_fv_046, 
  lvl_is_fv_047, 
  lvl_is_fv_048, 
  lvl_is_fv_049, 
  lvl_is_fv_050, 
  lvl_is_fv_051, 
  lvl_is_fv_052, 
  lvl_is_fv_053, 
  lvl_is_fv_054, 
  lvl_is_fv_055, 
  lvl_is_fv_056, 
  lvl_is_fv_057, 
  lvl_is_fv_058, 
 lvl_is_fv_059 };

DEF_STATIC_CONST_VAL_STRING(featval_0,"consonant");
DEF_STATIC_CONST_VAL_STRING(featval_1,"bilabial");
DEF_STATIC_CONST_VAL_STRING(featval_2,"plosive");
DEF_STATIC_CONST_VAL_STRING(featval_3,"voiceless");
DEF_STATIC_CONST_VAL_STRING(featval_4,"unaspirated");
DEF_STATIC_CONST_VAL_STRING(featval_5,"0");
DEF_STATIC_CONST_VAL_STRING(featval_6,"aspirated");
DEF_STATIC_CONST_VAL_STRING(featval_7,"nasal");
DEF_STATIC_CONST_VAL_STRING(featval_8,"voiced");
DEF_STATIC_CONST_VAL_STRING(featval_9,"labiodental");
DEF_STATIC_CONST_VAL_STRING(featval_10,"fricative");
DEF_STATIC_CONST_VAL_STRING(featval_11,"alveolar");
DEF_STATIC_CONST_VAL_STRING(featval_12,"dental");
DEF_STATIC_CONST_VAL_STRING(featval_13,"lateral");
DEF_STATIC_CONST_VAL_STRING(featval_14,"trill");
DEF_STATIC_CONST_VAL_STRING(featval_15,"palatal");
DEF_STATIC_CONST_VAL_STRING(featval_16,"velar");
DEF_STATIC_CONST_VAL_STRING(featval_17,"glottal");
DEF_STATIC_CONST_VAL_STRING(featval_18,"vowel");
DEF_STATIC_CONST_VAL_STRING(featval_19,"front");
DEF_STATIC_CONST_VAL_STRING(featval_20,"close");
DEF_STATIC_CONST_VAL_STRING(featval_21,"unrounded");
DEF_STATIC_CONST_VAL_STRING(featval_22,"short");
DEF_STATIC_CONST_VAL_STRING(featval_23,"long");
DEF_STATIC_CONST_VAL_STRING(featval_24,"nearclose");
DEF_STATIC_CONST_VAL_STRING(featval_25,"rounded");
DEF_STATIC_CONST_VAL_STRING(featval_26,"openmid");
DEF_STATIC_CONST_VAL_STRING(featval_27,"central");
DEF_STATIC_CONST_VAL_STRING(featval_28,"back");
DEF_STATIC_CONST_VAL_STRING(featval_29,"open");
DEF_STATIC_CONST_VAL_STRING(featval_30,"diph");
DEF_STATIC_CONST_VAL_STRING(featval_31,"silence");

static const cst_val * const lvl_is_featvals[] = {
 (cst_val *)&featval_0,
 (cst_val *)&featval_1,
 (cst_val *)&featval_2,
 (cst_val *)&featval_3,
 (cst_val *)&featval_4,
 (cst_val *)&featval_5,
 (cst_val *)&featval_6,
 (cst_val *)&featval_7,
 (cst_val *)&featval_8,
 (cst_val *)&featval_9,
 (cst_val *)&featval_10,
 (cst_val *)&featval_11,
 (cst_val *)&featval_12,
 (cst_val *)&featval_13,
 (cst_val *)&featval_14,
 (cst_val *)&featval_15,
 (cst_val *)&featval_16,
 (cst_val *)&featval_17,
 (cst_val *)&featval_18,
 (cst_val *)&featval_19,
 (cst_val *)&featval_20,
 (cst_val *)&featval_21,
 (cst_val *)&featval_22,
 (cst_val *)&featval_23,
 (cst_val *)&featval_24,
 (cst_val *)&featval_25,
 (cst_val *)&featval_26,
 (cst_val *)&featval_27,
 (cst_val *)&featval_28,
 (cst_val *)&featval_29,
 (cst_val *)&featval_30,
 (cst_val *)&featval_31,
 NULL };

const cst_phoneset lvl_is_phoneset = {
  "lvl_is",
  lvl_is_featnames,
  lvl_is_featvals,
  lvl_is_phonenames,
  "pau",
  60,
  lvl_is_fvtable,
  0  /* not freeable */
};
