/*******************************************************/
/**  Autogenerated lts rules (regex) for lvl_is     */
/**  from wfst/    */
/*******************************************************/

#include "cst_string.h"
#include "cst_lts.h"
#include "cst_lexicon.h"

const char * const lvl_is_lts_phone_table[91] = 
{
    "epsilon",
    "oei1",
    "aa1",
    "a1",
    "oeii1",
    "a0",
    "oei0",
    "ai1",
    "au1",
    "ai0",
    "au0",
    "aii1",
    "auu1",
    "auu0",
    "p",
    "k",
    "t",
    "T",
    "D",
    "ei0",
    "eii1",
    "ei1",
    "E1",
    "E0",
    "EE1",
    "j-E0",
    "j-EE1",
    "j-E1",
    "f",
    "m",
    "mz",
    "v",
    "c",
    "G",
    "x",
    "j",
    "k-v",
    "kh",
    "C",
    "h",
    "II1",
    "i1",
    "I0",
    "I1",
    "i0",
    "j-I0",
    "i0-j",
    "ii1",
    "ii1-j",
    "i1-j",
    "ch",
    "h-k",
    "lz",
    "t-l",
    "t-lz",
    "l",
    "J",
    "nz",
    "t-nz",
    "t-n",
    "n",
    "N",
    "Nz",
    "Jz",
    "OO1",
    "ou0",
    "O0",
    "O1",
    "Oi1",
    "Oi0",
    "ouu1",
    "j-ou0",
    "ou1",
    "ph",
    "h-p",
    "rz",
    "r",
    "s",
    "th",
    "h-t",
    "Y",
    "YY",
    "u1",
    "u0",
    "Yi",
    "uu1",
    "k-s",
    "oee1",
    "oe0",
    "oe1",
    NULL
};

const char * const lvl_is_lts_letter_table[38] = 
{
    "nothing",
    "#",
    "0",
    "a",
    "á",
    "b",
    "c",
    "d",
    "ð",
    "e",
    "é",
    "f",
    "g",
    "h",
    "i",
    "í",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "ó",
    "p",
    "r",
    "s",
    "t",
    "u",
    "ú",
    "v",
    "x",
    "y",
    "ý",
    "z",
    "þ",
    "æ",
    "ö",
    NULL
};

const cst_lts_addr lvl_is_lts_letter_index[35] = 
{
    0, /* a */
    213, /* á */
    318, /* b */
    324, /* c */
    325, /* d */
    330, /* ð */
    355, /* e */
    532, /* é */
    562, /* f */
    740, /* g */
    925, /* h */
    942, /* i */
    1053, /* í */
    1141, /* j */
    1151, /* k */
    1320, /* l */
    1449, /* m */
    1484, /* n */
    1819, /* o */
    1875, /* ó */
    1997, /* p */
    2067, /* r */
    2160, /* s */
    2266, /* t */
    2419, /* u */
    2493, /* ú */
    2563, /* v */
    2564, /* x */
    2565, /* y */
    2615, /* ý */
    2645, /* z */
    2646, /* þ */
    2652, /* æ */
    2687, /* ö */
    0
};

